### ISSUE TITLE
npm fail to install packages with dependencies on node 0.12.x

### ISSUE THREAD

**Issue by asafyish** [felixrieseberg/node12-azure#1]
Hi,

The script is not working when you have a dependency on a package that requires node 0.12,
Because of the warning "The iisnode.yml file explicitly sets nodeProcessCommandLine. Automatic node.js version selection is turned off." a really old node.js is selected, and the package cannot install.
you can try with https://github.com/msgpack/msgpack-node version 0.2.6.

**Comment by felixrieseberg** [comment]
Hey, thanks for reporting! You actually won't have to use this repo anymore to use Node 0.12 - you can instead just specify the engine parameter in your package.json. Node 12 is now preinstalled on all Azure Web Apps (formerly known as websites), so this is enough:

```
{ "engines": 
    { "node" : ">=0.12.0" } 
}
```

If you want to use a custom version of Node, this repo is still perfect - if that's the case, I'm happy to look into your problem :)

**Comment by asafyish** [comment]
I am using this repo for specifying --harmony flag, couldn't find other way.
Anyway, the problem is not in this script... it's while building on any node.js version.
